sudo: true
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

script: 
  # Build and run Boost.Test
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_qtest_boost_test.pro
  - make
  - ./travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_qtest_boost_test
  # Build and run QTest
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_qtest_qtest.pro
  - make
  - ./travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_qtest_qtest
  # Build (but not run) 'real' program
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_qtest.pro
  - make
  # Get code coverage
  - ./get_code_cov.sh
  - codecov
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)